[package]
name = "tokio-inherit-task-local"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.2.8"
tokio = { version = "1.37.0", features = ["rt"] }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["rt", "macros"]}
